version: '3.1'

volumes:
  music_files_volume:
    external: true

services:
  musicplayer:
    # image: app
    container_name: musicplayer
    build:
      context: .
      dockerfile: Dockerfile
    restart: always  
    volumes:
      - .:/musicplayer
      - music_files_volume:/musicplayer/files
    ports:
      - 8001:8001
    networks:
      - music_network

networks:
  music_network:
    external: true
      